apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-1
  namespace: logging-wrapper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-1
  template:
    metadata:
      labels:
        app: kafka-1
    spec:
      containers:
        - name: kafka-1
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 9091
            - containerPort: 29091
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-1:9091,PLAINTEXT_HOST://localhost:29091"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9091,PLAINTEXT_HOST://0.0.0.0:29091"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "2"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1
  namespace: logging-wrapper
spec:
  selector:
    app: kafka-1
  ports:
    - name: kafka-broker
      protocol: TCP
      port: 9091
      targetPort: 9091
    - name: kafka-external
      protocol: TCP
      port: 29091
      targetPort: 29091
  type: ClusterIP
