apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: timescaledb
  namespace: logging-wrapper
spec:
  serviceName: "timescaledb"
  replicas: 1
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
        - name: timescaledb
          image: timescale/timescaledb:latest-pg15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "logs"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: timescale-storage
      volumes:
        - name: timescale-storage
          persistentVolumeClaim:
            claimName: timescale-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: timescaledb
  namespace: logging-wrapper
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: timescaledb
