apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-1
  namespace: logging-wrapper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-1
  template:
    metadata:
      labels:
        app: kafka-1
    spec:
      containers:
        - name: kafka-1
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 9091
            - containerPort: 29091
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-1:9091,PLAINTEXT_HOST://localhost:29091"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1
  namespace: logging-wrapper
spec:
  ports:
    - port: 9091
      targetPort: 9091
  selector:
    app: kafka-1
