apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-2
  namespace: logging-wrapper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-2
  template:
    metadata:
      labels:
        app: kafka-2
    spec:
      containers:
        - name: kafka-2
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 9092
            - containerPort: 29092
          env:
            - name: KAFKA_BROKER_ID
              value: "2"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:29092"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "2"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-2
  namespace: logging-wrapper
spec:
  selector:
    app: kafka-2
  ports:
    - name: kafka-broker
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: kafka-external
      protocol: TCP
      port: 29092
      targetPort: 29092
  type: ClusterIP
