apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-2
  namespace: logging-wrapper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-2
  template:
    metadata:
      labels:
        app: kafka-2
    spec:
      containers:
        - name: kafka-2
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 9092
            - containerPort: 29092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:29092"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-2
  namespace: logging-wrapper
spec:
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: kafka-2
