apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: logging-wrapper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "local"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka-1:9091,kafka-2:9092"
            - name: KAFKA_CLUSTERS_0_ZOOKEEPER
              value: "zookeeper:2181"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: logging-wrapper
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: kafka-ui
