apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
  namespace: logging-wrapper
spec:
  serviceName: "neo4j"
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j
          image: neo4j:latest
          env:
            - name: NEO4J_AUTH
              value: "neo4j/H7t-YFBxjSBWxIFnhO7OaGAjKwk6c-q5wxq_yP95E1M"
          volumeMounts:
            - mountPath: /data
              name: neo4j-storage
      volumes:
        - name: neo4j-storage
          persistentVolumeClaim:
            claimName: neo4j-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: logging-wrapper
spec:
  ports:
  - name: bolt
    port: 7687
    targetPort: 7687
  - name: http
    port: 7474
    targetPort: 7474
  selector:
    app: neo4j
